name = "Advent"
version = "0.1.0"
defaultTargets = ["advent"]

[[lean_lib]]
name = "Advent"

[[lean_exe]]
name = "advent"
root = "Main"

[[require]]
name = "batteries"
git = "git@github.com:leanprover-community/batteries.git"
rev = "v4.14.0"
